[visualization]
export = true
export_interval = 10

   [[visualize_sim_object]]
   name = "GRNCell"
   additional_data_members = [ "diameter_", "cell_color_", "counter_sub_quant_"]


#   [[visualize_diffusion]]
#   name = "Substance"
#   gradient = true
